### ISSUE TITLE
Typo in Manifest.json (manifest.webmanifest)

### ISSUE THREAD

**Issue by RaSan147** [TheUndo/Atsumaru#11]
**Describe the bug**
In website `manifest.webmanifest` and in github `src/frontend/assets/oldmanifest.json`, both place `Manwha` typo appeared (i also thought it was the right spelling until yesterday)

The correct spelling is `Manhwa` (based on google)

**To Reproduce**
See yourself 😅

**Expected behavior**
Replace....

**Screenshots**
![Screenshot_2022-07-27-00-26-43-35](https://user-images.githubusercontent.com/34002411/181084643-e2264795-bf81-48de-80b6-6aec9b2b846e.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RaSan147** [comment]
@TheUndo 😅 The find and replace worked but relative Capitalization is broken (line manga, Manhwa... Again MANGA | Manhwa), kindly revise

**Comment by TheUndo** [comment]
@RaSan147 Yeah got it. Thanks for your interest in hunting down typos, in the future, for such low priority problems sending a PR with the typos corrected is better than opening issues.

**Comment by RaSan147** [comment]
On mobile right now, will try to hunt some more when using PC and PR (and gain some inspiration for my similar project😅)
