### ISSUE TITLE
Its not an issue just want to communicate

### ISSUE THREAD

**Issue by nightfury1720** [TheUndo/Atsumaru#13]
**Describe the bug**
//this is not a bug

The website is awesome and I really appreciate all the technical implementations to make it more performant

I wish to contribute to the project but I am not sure whether it is still open? can you pls guide me on how to get started?
(this will be my first time contributing so sorry if this is not the right way to ask for this)

**Comment by TheUndo** [comment]
If you're familiar with React and TypeScript there should be no issues with contributing, just clone the project and follow the instructions in the readme. If you run into any problems open a new issues with details and I'll help you, alternatively you can join the Discord server and message me there.

Thanks!
